### ISSUE TITLE
Data input array for combined gpa and trajectory analysis (4D)

### ISSUE THREAD

**Issue by bernard-liew** [geomorphR/geomorph#13]
Hi,

I am intending to do a combined GPA and trajectory analysis for 3D biomechanics analysis of the foot. I hope to seek some clarity on a rather trivial issue of input data array.

For GPA, the documentary says a p x k x n array
For traj analysis, it says either a matrix  (n x [p x k]), or a 3D array (p x n x k)

Assuming, p = landmark, k = 3 axis, n = 60 subjects (2 groups of 30), c = 100 points in a walking cycle.

Question:
1) Is there a common way to create an array or matrix for a 4 mode data (landmark, axis, subjects, cycle) suitable for gpa and traj analysis?

Kind regards,
Bernard

**Comment by mlcollyer** [comment]
Bernard,

The p in trajectory analysis does not refer to landmarks but trajectory points and k the dimensions (variables) at each point. In your case, I think p = 100, k = 3, and n = 60 x 2 and should be arranged in a matrix that way. 

Mike

**Comment by bernard-liew** [comment]
Ahhh...

Thanks Mike, just to reiterate,

if I have 20 landmarks, 3 cartesian planes, 100 trajectory points, 60 subjects, it is a

100 x [20*3] x 60, array?

Kind regards,
Bernard

**Comment by mlcollyer** [comment]
If your trajectory is already defined and not supposed to be estimated by a factorial model, then each subject is a trajectory.  Each of those subjects has a trajectory of 100 points?  (I assume following GPA.)  And each point is a vector, which describes a 20 point configuration in 3 dimensions.  Thus, the matrix is 60 x [100 x [20*3]].  Your trajectories have 6000 points total, as any one point in the data space has 60 variables and you have 100 points in that space.

Note that it does not matter entirely how you arrange the 100 points of 20 x 3 coordinates, as long as it is done the same way for each subject.  Focusing on the 20 x 3 parts, you need to make this a string of 60 values.  Can by 20 x, then 20 y, then 20 z, or can be x1, y1, z1, x2, y2, z2, …, as long as for each of the 100 points and for each subject it is done the same way.  You have a p = 100 and a k = 60, regardless.  I would stay away from the array approach because your subjects are full trajectories and if you can guarantee the rows of a matrix match subjects, you have better control for making sure it is arranged correctly.

Cheers!
Mike

**Comment by bernard-liew** [comment]
Thanks Mike,

Yes the trajectories are defined. This is really useful. I assume this data format of 60 x [100 x [20*3]] should be similar used for the initial GPA step too?

Cheers,
Kind regards,
Bernard

**Comment by mlcollyer** [comment]
Bernard,

No, your data still need to be formatted as if the landmark configurations are independent for gpagen. Thus, a 3D array with dimensions 20 x 3 x [100 x 60]. 

Mike
