### ISSUE TITLE
ProcD.pgls - error w/ instances of single observations? 

### ISSUE THREAD

**Issue by sulserrb** [geomorphR/geomorph#32]
Hello all - 

After updating R and the Geomorph package, I'm having some issues with running ProcD.pgls with data frames involving a single instance of a given observation, giving me the following error code:

`"Error in LM$X %*% LM$gls.coefficients : non-conformable arguments"`

I should note that my code appeared to run successfully prior to updating my packages, and that running ProcD.lm with an identical dataset works just fine. Unless I'm committing some statistical faux-pas I'm unaware of,  I suspect this issue is similar to  [this post](https://groups.google.com/g/geomorph-r-package/c/IQ1kh2X3Hok/m/4Cn6k05FCQAJ), which seems to involve GLS and some aspect of RRPP as well: 

R version: 4.0.5
Geomorph version: 4.0.0
RRPP version: 1.0.0

```
library(geomorph)
data(plethspecies)

#set up single/multi observations
discretes <- data.frame(single_instance = c("1", "1", "1", "1", "1", "2", "2", "2", "3"), 
                             multi_instance = c("1", "1", "1", "1", "1", "2", "2", "3", "3"))

Y.gpa<-gpagen(plethspecies$land)    
plethgdf <- geomorph.data.frame(Y.gpa, phy = plethspecies$phy, single = discretes$single_instance,
                                multi = discretes$multi_instance  )

#Run with multiple observations of all characters  (works)
pleth.lm <- procD.lm(coords ~ Csize * multi, data = plethgdf)
pleth.pgls <- procD.pgls(coords ~ Csize * multi, phy = phy, data = plethgdf)
                        
#Run with one single observation of one character (issues in pgls only)
pleth.lm <- procD.lm(coords ~ Csize * single, data = plethgdf)
pleth.pgls <- procD.pgls(coords ~ Csize * single, phy = phy, data = `plethgdf)'
```` 

Let me know if there's anything else I can provide that might be helpful! 

~Ben

**Comment by mlcollyer** [comment]
Ben,

We will have to look into why this blows up.  We try to prevent illogical analyses from blowing up, but it’s like disarming a bomb.  You set the bomb, not so much because of the “single” variable, but because you asked to have coefficients for its interaction with Csize.  Without replication there is no interaction.  This is why you get the warning that the X matrix has been reduced from 6 to 5 columns, but apparently that is not enough to save the analysis.  I’m not sure why.  In verifying with lm.fit, that function finds 5 coefficients.  It looks like somewhere in the process the superfluous 6th variable is retained.

But you could do yourself a favor and change the formula to not ask for interactions that cannot occur.  The formula is illogical.  Although the function tries to work in spite of bad formulae, some times bad formulae will get the best of the function.

Cheers!
Mike

**Comment by sulserrb** [comment]
Hi Mike - 

Ah yes that would do it, wouldn't it - fixing the formula indeed runs without a hitch, apologies for not catching that sooner! Thank you for the help and the quick response! 

Best, 
~Ben
