### ISSUE TITLE
Issue with plot.gm.prcomp

### ISSUE THREAD

**Issue by sjm5467** [geomorphR/geomorph#35]
I used to run code to create a tangent space using plot.gm.prcomp and then us plot3d to create a great rotatable PCA plot. Now when I run my code I get:

Error in plot.gm.prcomp(scaled_points, axis1 = 1, axis2 = 2, warpgrids = FALSE,  : 
  could not find function "plot.gm.prcomp"

Did this function change? Thanks!

**Comment by mlcollyer** [comment]
You should not use plot.gm.prcomp(my.gm.prcomp.object), but use plot(my.gm.prcomp.object).  The plot.gm.prcomp function is an S3 generic function <http://adv-r.had.co.nz/S3.html>  meaning one uses “plot” and it knows what to do because of the gm.prcomp class of the object.

I believe a few versions back, CRAN changed how R handles S3 generics.  It used to be that S3 functions were exported but now they are considered internal, or one has to try to explicitly export them.  An alternative is to use:

geomorph:::plot.gm.prcomp(my.gm.prcomp.object)

if you do not want to have the function treated as an S3 function.

Mike

PS, if the link did not work: http://adv-r.had.co.nz/S3.html <http://adv-r.had.co.nz/S3.html>
