### ISSUE TITLE
Read 2D (X,Y coordinates) data file

### ISSUE THREAD

**Issue by lrocax** [geomorphR/geomorph#36]
I have several data files that contain each an one object X,Y coordinates. Is there a way to read them and convert them to geomorph.data.frame. The data will not contain SCALE. The readland.fcsv does not fit to this purpose.

The structure of the data file is like this:
x,y
1,10
40.5,110.5
75.5,91.2
100.2,61.9
130.5,21.6 

Thanks a lot.

**Comment by antkal** [comment]
You need to combine base R functions for this, this is not a geomorph-specific issue. Try a cycle with all your files and read.csv, for instance. You may look into the code of readmulti.nts for an example (although that is a more complex function due to different nts possible formats that exist).

Hope this helps.
