### ISSUE TITLE
readmulti.tps error

### ISSUE THREAD

**Issue by JohnSal1** [geomorphR/geomorph#37]
Hi,

I trying to read multiply TPS files using this script:
```
require(geomorph) 
filelist <- list.files("E:/",pattern = "*.tps") 
mydata <- readmulti.tps(filelist,specID = c("ID", "imageID"),readcurves = FALSE)
```

but I get this error:
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file '2013_Obj.tps': No such file or directory

Any idea why?

**Comment by antkal** [comment]
Due to shortness of time I am just guessing here, but I think you are trying to use * as you would in unix programming, and in this case you would just need pattern = ".tps" to set the list of files. Have you checked that filelist ends up with what you imagine inside it? Also, in readmulti.tps you need to choose a single option for the specID argument.

Hope this helps. If it doesn´t, you would need to share your files with me somehow so I can have a look if you want.
