### ISSUE TITLE
Issue with procD.lm 

### ISSUE THREAD

**Issue by apwoodbailey** [geomorphR/geomorph#38]
Hi all, 

I am trying to run this: 
> procD.lm(GPA$rotated~classifiers$locomotor_type,iter=9999,SS.type="III")

But get the following error code:
Error in `rownames<-`(`*tmp*`, value = nms) : 
  attempt to set 'rownames' on an object with no dimensions

This works on an older version of Geomorph but not on 4.0.1. It appears to be an issue with procD.lm specifically.

Any idea what to do?

Cheers

**Comment by mlcollyer** [comment]
You might try looking into geomorph.data.frame.  The issue is one we would not like to happen, but the update for geomorph 4.0.1 was thrust upon us because of the R 4.1 update, and the loss of observation names in some functions.  This error is caused by trying to assign names to a missing object.  But why is the object missing?   We will have to investigate this; it is probably the inadvertent result of one of our updates.

However, you are taking risks — anytime and not just with geomorph — when you ask R functions to try to figure out in which environment you are working.  With your formula, you are telling R to work in the global environment and there, go digging for objects within objects (as made clear by the $ operator).  With a geomorph data frame, the environment is unambiguous.

If the error persists after trying a geomorph.data.frame, we would like to know.  We will investigate if we can find a patch for this lacking environment definition issue, but it might be an issue that can be avoided with a precise definition of data frame.

Mike
