### ISSUE TITLE
Error in reading a TPS file

### ISSUE THREAD

**Issue by JohnSal1** [geomorphR/geomorph#45]
Hi,

I extracted some semi-landmarks and save them as TPS file.
While reading the TPS file (attached as ZIP) I got this error "No curves detected; all points appear to be fixed landmarks." and all the file is filled with NA.

Code used:
x <- readland.tps("E:/pi01Angle.tps", specID = c("imageID"),negNA = FALSE,  readcurves = TRUE,  warnmsg = TRUE)

[pi01Angle.zip](https://github.com/geomorphR/geomorph/files/13597013/pi01Angle.zip)

Any idea why?

**Comment by mlcollyer** [comment]
Your tps file includes a scale argument but is missing a value.  If you provide a value for the scale or remove the argument, the function produces a configuration.

Mike

**Comment by JohnSal1** [comment]
Thanks a lot. I removed the scale.

**Comment by mlcollyer** [comment]
This is an issue we need to fix but you should be okay if you remove the warnmsg argument from your function.  The problem is that within the readmulti.tps function, we suppress warning messages for readland.tps, and when you requested the same action, R does not like to be told twice to do something.

Thanks for the alert!

Mike
