### ISSUE TITLE
Negative values are not imported as NA in geomorph 4.0.7

### ISSUE THREAD

**Issue by dartcesan** [geomorphR/geomorph#47]
Hi, I'm having an issue reading a TPS file with missing landmarks.
I am using this code:
readland.tps("LandmarksNeg.tps",negNA = TRUE, specID = "ID")
to read this file
[LandmarksNeg.zip](https://github.com/geomorphR/geomorph/files/14879867/LandmarksNeg.zip)

I never had a problem before updating to geomorph version 4.0.7.
Could you help me solve this?

**Comment by deanadams** [comment]
Please reinstall from github and try again.  About 2 weeks ago this issue was identified and resolved.

Dean

Dr. Dean C. Adams
Distinguished Professor of Evolutionary Biology
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

From: dartcesan ***@***.***>
Sent: Thursday, April 4, 2024 11:34 PM
To: geomorphR/geomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/geomorph] Negative values are not imported as NA in geomorph 4.0.7 (Issue #47)


Hi, I'm having an issue reading a TPS file with missing landmarks.
I am using this code:
readland.tps("LandmarksNeg.tps",negNA = TRUE, specID = "ID")
to read this file
LandmarksNeg.zip<https://github.com/geomorphR/geomorph/files/14879867/LandmarksNeg.zip>

I never had a problem before updating to geomorph version 4.0.7.
Could you help me solve this?
