### ISSUE TITLE
Landmark coordinates input with digitize2d() are missing

### ISSUE THREAD

**Issue by JVAdams** [geomorphR/geomorph#9]
I am using the `digitize2d()` function, inputting the scale and the landmarks with a couple of jpg files.  Everything seems to work fine visually and interactively, but the landmark coordinates are not being saved.  There are many (or in the case below, all) coordinates with missing values

I thought it might be because I had rescaled the plot window in RStudio.  But keeping it fixed didn't change the result.  Then I thought it might be the RStudio window in general, so I tried it in R.  There I got an error message after the call to `digitize2d()`:

> Error in A[, , i] : subscript out of bounds

Any suggestions?

I'm using R version 3.3.1, RStudio version 1.0.44

**Comment by deanadams** [comment]
Jean,

Difficult to troubleshoot without seeing files etc. When digitize2d is first run on a new set of specimens, it creates a file with all 0 for the landmarks. It then fills things in as it goes. So I’m not sure at all why things are NA.

Have you installed from the Stable version on Github and tried again?

Dean

Dr. Dean C. Adams
Professor
Department of Ecology, Evolution, and Organismal Biology
       Department of Statistics
Iowa State University
www.public.iastate.edu/~dcadams/<http://www.public.iastate.edu/~dcadams/>
phone: 515-294-3834

**Comment by deanadams** [comment]
One other thing that might help track down the issue. After digitizing open the tps file in a text editor. What precisely is in it?  That will help sort out if you are digitizing correctly or whether the issue is in reading your file.

Dean

Dr. Dean C. Adams
Professor
Department of Ecology, Evolution, and Organismal Biology
       Department of Statistics
Iowa State University
www.public.iastate.edu/~dcadams/<http://www.public.iastate.edu/~dcadams/>
phone: 515-294-3834
